Add dynamics to website
abelagza/mobile_version_skeleton pull request #13
Opened 2022-04-12 21:28 UTC by abelagza

# Portfolio: mobile menu 

#### In this milestone we:

- Implemented JS for the burger button.
- Fixed HTML tags
- Fixed CSS styling sheet
- Fixed linters

2022-04-12 22:21 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-12 22:21 UTC, Omar-Muhamad commented on style.css
> +
- [ ] Please make the mobile menu background cover the whole page to be like the Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/163064298-afbdf6c8-c54b-4878-8c84-0b81c330d975.png) | ![image](https://user-images.githubusercontent.com/68796232/163064203-fe60845a-29c3-45d1-a3a4-84c4932e3bf8.png)  |

2022-04-14 06:27 UTC, abelagza commented
# Portfolio: mobile menu
#### In this milestone I:

- Fixed website styling according to Figma's.

2022-04-14 06:34 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-16 14:00 UTC, merged